export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SET_ADD_TO_CART: "SET_ADD_TO_CART",
  CLEAR_CART: "CLEAR_CART",
  REMOVE_ITEM: "REMOVE_ITEM",
  TOGGLE_AMOUNT: "TOGGLE_AMOUNT",
  SET_CATEGORY: "SET_CATEGORY",
};
